name: "Build & Release" # You can name it as you want
on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - dev
      - main
jobs: # Telling what jobs we need to happen
  build: # Specify the building name and machine
    name: Build & Release
    runs-on: windows-latest
    steps:
      #1 Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4
      #2 Set up JDK
      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
          cache: "gradle"
          cache-dependency-path: | # optional
            sub-project/*.gradle*
             sub-project/**/gradle-wrapper.properties
      - run: ./gradlew build --no-daemon
      #3 Set up Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.13.7"
      #4 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get
      #5 run test
      - name: Test flutter app
        run: flutter test
      #6 Build app
      - name: Build flutter app
        run: flutter build apk --release
      #7 build aab
      - name: Build appBundle
        run: flutter build appbundle
      #8 build Ipa
      - name: Build Ipa
        run: flutter build ipa --no-codesign
      - name: Compress Archives and IPAs
        run: |
          cd build
          tar -czf ios_build.tar.gz ios
      #9 get those build to be avaible to download
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
            build/ios_build.tar.gz
      #10 create release with those de build
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/app/outputs/bundle/release/app-release.aab,build/i.*os_build.tar.gz"
          tag: v1.0${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
